# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lizard_auth_server.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lizard_auth_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('unique_id', models.CharField(default=lizard_auth_server.models.create_new_uuid, max_length=32, unique=True, verbose_name='unique id')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'verbose_name': 'company',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lizard_auth_server.Company', verbose_name='company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'profiles',
                'verbose_name': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name used to refer to this site.', max_length=255, verbose_name='name')),
                ('available_to', models.ManyToManyField(blank=True, related_name='sites', to='lizard_auth_server.Company', verbose_name='available to')),
            ],
            options={
                'verbose_name_plural': 'sites',
                'verbose_name': 'site',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'user profile (old style)', 'verbose_name_plural': 'user profiles (old style)'},
        ),
        migrations.AddField(
            model_name='company',
            name='administrators',
            field=models.ManyToManyField(blank=True, help_text='Can manage other user profiles.', related_name='admin_companies', to='lizard_auth_server.Profile', verbose_name='administrators'),
        ),
        migrations.AddField(
            model_name='company',
            name='guests',
            field=models.ManyToManyField(blank=True, help_text='Guests or external users.', related_name='guest_companies', to='lizard_auth_server.Profile', verbose_name='guests'),
        ),
    ]
