# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 14:31
from __future__ import unicode_literals
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('lizard_auth_server', '0002_auto_20160701_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='lizard_auth_server.Organisation', verbose_name='organisations'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='lizard_auth_server.OrganisationRole', verbose_name='roles (via organisation)'),
        ),
    ]
