# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lizard_auth_server', '0003_auto_20160818_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['is_activated', '-created_at', 'email'], 'verbose_name': '(invitation)', 'verbose_name_plural': '(invitation)'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name'], 'verbose_name': '(organisation)', 'verbose_name_plural': '(organisations)'},
        ),
        migrations.AlterModelOptions(
            name='organisationrole',
            options={'verbose_name': '(organisation-role-mapping)', 'verbose_name_plural': '(organisation-role-mappings)'},
        ),
        migrations.AlterModelOptions(
            name='portal',
            options={'ordering': ('name',), 'verbose_name': '(portal)', 'verbose_name_plural': '(portals)'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['portal', 'name'], 'verbose_name': '(role)', 'verbose_name_plural': '(roles)'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('-created',), 'verbose_name': '(authentication token)', 'verbose_name_plural': '(authentication tokens)'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': '(user profile)', 'verbose_name_plural': '(user profiles)'},
        ),
    ]
