# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 13:36
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lizard_auth_server', '0005_auto_20160824_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
    ]
