# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lizard_auth_server', '0007_portal_already_migrated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='already_migrated',
        ),
        migrations.AddField(
            model_name='organisation',
            name='already_migrated',
            field=models.BooleanField(default=False, verbose_name='already migrated'),
        ),
    ]
