# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 09:32
from __future__ import unicode_literals
from django.db import migrations
from django.db import models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lizard_auth_server', '0008_auto_20160824_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='lizard_auth_server.Company', verbose_name='company'),
        ),
    ]
