# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 08:35
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lizard_auth_server", "0009_auto_20160825_1132"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ("name",),
                "verbose_name": "company",
                "verbose_name_plural": "companies",
            },
        ),
        migrations.AlterModelOptions(
            name="site",
            options={
                "ordering": ("name",),
                "verbose_name": "site",
                "verbose_name_plural": "sites",
            },
        ),
    ]
