# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 13:50
from __future__ import unicode_literals
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('lizard_auth_server', '0012_auto_20160920_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name'], 'verbose_name': 'organisation', 'verbose_name_plural': 'organisations'},
        ),
        migrations.AlterModelOptions(
            name='portal',
            options={'ordering': ('name',), 'verbose_name': 'portal', 'verbose_name_plural': 'portals'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterField(
            model_name='portal',
            name='allowed_domain',
            field=models.CharField(default='unused in v2 api', help_text='Allowed domain suffix for redirects using the next parameter. Multiple, whitespace-separated suffixes may be specified.', max_length=255, verbose_name='allowed domain(s)'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='redirect_url',
            field=models.CharField(default='http://unused.in/v2/api', help_text='URL used in the SSO redirection.', max_length=255, verbose_name='redirect url'),
        ),
    ]
