# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 13:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lizard_auth_server", "0013_auto_20160921_1550"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="already_migrated",
        ),
    ]
