# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 06:54
from __future__ import unicode_literals
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('lizard_auth_server', '0014_remove_organisation_already_migrated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='street',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='town',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisations',
            field=models.ManyToManyField(blank=True, help_text='only used in the old v1 api', related_name='user_profiles', to='lizard_auth_server.Organisation', verbose_name='organisations'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portals',
            field=models.ManyToManyField(blank=True, help_text='only used in the old v1 api', related_name='user_profiles', to='lizard_auth_server.Portal', verbose_name='portals'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='only used in the old v1 api', related_name='user_profiles', to='lizard_auth_server.OrganisationRole', verbose_name='roles (via organisation)'),
        ),
    ]
