# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-17 15:33
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("lizard_auth_server", "0016_auto_20171208_1446"),
    ]

    operations = [
        migrations.AddField(
            model_name="portal",
            name="allow_migrate_user",
            field=models.BooleanField(
                default=False, help_text="Whether to allow the migrate_user v2 api"
            ),
        ),
    ]
