# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-17 15:40
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("lizard_auth_server", "0017_portal_allow_migrate_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="migrated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The last time the cognito/migrate_user was called for this user",
                null=True,
            ),
        ),
    ]
